apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      imagePullSecrets:   
      - name: acr-secret  
      containers:
      - name: flask-app
        image: devopsalert.azurecr.io/flask-log-app:v1
        imagePullPolicy: Always  
        ports:
        - containerPort: 5000
          protocol: TCP
        resources: {}
